### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by burakwalkerofficial** [threat9/routersploit#608] opened 2019-08-16 22:16 UTC
! ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY !

Exception in thread thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/routersploit/routersploit/modules/creds/generic/ftp_default.py", line 52, in target_function
    username, password = data.next().split(":")
ValueError: too many values to unpack (expected 2)

Exception in thread thread-0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/routersploit/routersploit/modules/creds/generic/ssh_default.py", line 53, in target_function
    username, password = data.next().split(":")
ValueError: too many values to unpack (expected 2)

**Comment by ttran49** [comment] 2019-08-21 21:53
Duplicate of #604

**Comment by lucyoa** [comment] 2019-08-31 12:25
Closing, duplicate #604

**Closed by lucyoa** 2019-08-31 12:25 UTC
Labels: duplicate
